import { Inter } from "next/font/google";
import { Stack, useColorMode } from "@chakra-ui/react";
import PostDetail from "@/src/components/commons/combine/postDetatil";
import CustomTabs from "@/src/components/commons/combine/customTabs";
import { withAuth } from "@/src/components/commons/customhooks/withAuth";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

const exam = {
  username: "John Doe",
  content: "This is a comment.",
  avatarUrl: "",
  town: "교동",
  time: "지금",
};

const data = {
  town: "gyodong",
  time: "1h",
  likeCount: 12,
  commentCount: 5,
  contents:
    "With Chakra UI, I wanted to sync the speed of development with thespeed of design. I wanted the developer to be just as excited as thedesigner to create a screen.",
  imgUrl:
    "https://images.unsplash.com/photo-1531403009284-440f080d1e12?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80",
  avatarUrl: "https://naver.com",
  username: "Chan Pa",
  isLiked: true,
};

const data2 = {
  avatarUrl: "Hello how are you?",
  username: "Chansoo Park",
  town: "suwon",
  isFriend: true,
  friendsCount: 5,
};

function HomePage() {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CustomTabs
        tabList={[
          "posts",
          "Liked",
          "interested",
          "interested",
          "interested",
          "interested",
          "posts",

          "interested",
        ]}
      >
        <Stack gap="0.5rem" marginTop="2px">
          {Array.from({ length: 9 }, (_, index) => (
            <PostDetail key={index} postDetailData={data} />
          ))}
        </Stack>
      </CustomTabs>
    </>
  );
}

export default withAuth(HomePage);
